version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    network_mode: host   
    #networks:
    #  - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html  # This mounts the frontend files to Nginx
    networks:
      - app-network

  
networks:
  app-network:
    driver: bridge
